apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-acskoahn
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-acskoahn:b1369a8283ec06f51a52de63acd9f59e1db83e7c@sha256:80f9790d55ab6d5c6437423ea6cf1a023020f32ddae26cb6826d6119a6deaf9d
        name: container-image  
